### ISSUE TITLE
Cannot open a titandb instance by following your example in the blog

### ISSUE THREAD

**Issue by gnatseira** [tikv/titan#155]
I cloned titan by git, then I used the following commands to compile it.
```shell
mkdir build
cd build
cmake ..
make
```
Then I got two library files `libtitan.a` and `librocksdb.a`.
I wrote the following code to run an example from your blog:
```C

#include <titan/db.h>

int main() {
    rocksdb::titandb::TitanDB* db;
    rocksdb::titandb::TitanOptions options;
    options.create_if_missing = true;
    rocksdb::Status status = rocksdb::titandb::TitanDB::Open(options, "/tmp/testdb", &db);
    return 0;
}
```

The sample is compiled by using the following command, and we can get a executable file named `a.out`.
```shell
g++ -std=c++11 -pthread test.cc -I/root/git/titan/include -I/root/git/titan/build/rocksdb -L /root/git/titan/build/ -ltitan -L /root/git/titan/build/rocksdb/ -lrocksdb
```
But when `./a.out` is used, it shows `segmentation fault`. 
So I want to ask whether the blog post is too old to use. 
How can I run a correct example?

Thank you so much!

**Comment by yiwu-arbug** [comment]
Nothing wrong with your test code it seems. Are you able to get a stack trace of the segfault? Maybe using gdb? Thanks.

**Comment by gnatseira** [comment]
The gdb information is shown as follows:
```shell

(gdb) b rocksdb::titandb::TitanDB::Open
Breakpoint 1 at 0x407f9c (2 locations)
(gdb) r
Starting program: /root/a.out 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Breakpoint 1, 0x0000000000407f9c in rocksdb::titandb::TitanDB::Open(rocksdb::titandb::TitanOptions const&, std::string const&, rocksdb::titandb::TitanDB**) ()
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7_6.6.x86_64 glibc-2.17-292.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64
(gdb) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b92cbb in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /lib64/libstdc++.so.6
(gdb) up
#1  0x000000000040b77a in rocksdb::titandb::TitanDBOptions::TitanDBOptions(rocksdb::titandb::TitanDBOptions const&) ()
```

**Comment by gnatseira** [comment]
More information
```shell

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b92cbb in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /lib64/libstdc++.so.6
(gdb) up 
#1  0x000000000040b77a in rocksdb::titandb::TitanDBOptions::TitanDBOptions(rocksdb::titandb::TitanDBOptions const&) ()
(gdb) up
#2  0x0000000000407fd9 in rocksdb::titandb::TitanDB::Open(rocksdb::titandb::TitanOptions const&, std::string const&, rocksdb::titandb::TitanDB**) ()
(gdb) up
#3  0x0000000000406d06 in main () at test.cc:8
8                       rocksdb::titandb::TitanDB::Open(options, "/tmp/testdb", &db);
```
I’m not sure why it fails. Is it a compiler error? I’m using centos 7 and gcc 4.8.5.

**Comment by gnatseira** [comment]
Sorry to disturb you. I found what I have done incorrectly and it can be solve. Thank you.
