### ISSUE TITLE
Segment fault when creates TitanCompactionFilter

### ISSUE THREAD

**Issue by youjiali1995** [tikv/titan#180]
version: master. I don't know how to reproduce it and the core dump is in root@172.16.5.71:/data2/core.133685

```
(gdb) bt
#0  0x0000555557099f06 in TitanCompactionFilter (skip_value=false, blob_storage=..., owned_filter=<synthetic pointer>,
    original=0x0, cf_name=..., db=<optimized out>, this=0x7fffd722a190)
    at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/d60144d/librocksdb_sys/libtitan_sys/titan/src/compaction_filter.h:27
#1  rocksdb::titandb::TitanCompactionFilterFactory::CreateCompactionFilter (this=0x7ffff6b90fd8, context=...)
    at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/d60144d/librocksdb_sys/libtitan_sys/titan/src/compaction_filter.h:162
#2  0x00005555571e61ef in rocksdb::Compaction::CreateCompactionFilter (this=<optimized out>)
    at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/d60144d/librocksdb_sys/rocksdb/db/compaction/compaction.cc:528
#3  0x00005555571fa3c1 in rocksdb::CompactionJob::ProcessKeyValueCompaction (this=this@entry=0x7fffd8d58fc0,
    sub_compact=0x7fffd723c000)
    at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/d60144d/librocksdb_sys/rocksdb/db/compaction/compaction_job.cc:820
#4  0x00005555571fc8a0 in rocksdb::CompactionJob::Run (this=this@entry=0x7fffd8d58fc0)
    at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/d60144d/librocksdb_sys/rocksdb/db/compaction/compaction_job.cc:590
#5  0x0000555556f1e1f1 in rocksdb::DBImpl::BackgroundCompaction (this=this@entry=0x7ffff6b5c400,
    made_progress=made_progress@entry=0x7fffd8d5942e, job_context=job_context@entry=0x7fffd8d59450,
    log_buffer=log_buffer@entry=0x7fffd8d59620, prepicked_compaction=prepicked_compaction@entry=0x0,
    thread_pri=thread_pri@entry=rocksdb::Env::LOW)
    at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/d60144d/librocksdb_sys/rocksdb/db/db_impl/db_impl_compaction_flush.cc:2759
#6  0x0000555556f22bb2 in rocksdb::DBImpl::BackgroundCallCompaction (this=this@entry=0x7ffff6b5c400,
    prepicked_compaction=prepicked_compaction@entry=0x0, bg_thread_pri=bg_thread_pri@entry=rocksdb::Env::LOW)
    at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/d60144d/librocksdb_sys/rocksdb/db/db_impl/db_impl_compaction_flush.cc:2317
#7  0x0000555556f230aa in rocksdb::DBImpl::BGWorkCompaction (arg=<optimized out>)
    at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/d60144d/librocksdb_sys/rocksdb/db/db_impl/db_impl_compaction_flush.cc:2092
#8  0x000055555722ae9a in rocksdb::ThreadPoolImpl::Impl::BGThread (this=this@entry=0x7fffe7292180,
    thread_id=thread_id@entry=1)
    at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/d60144d/librocksdb_sys/rocksdb/util/threadpool_imp.cc:266
#9  0x000055555722b08e in rocksdb::ThreadPoolImpl::Impl::BGThreadWrapper (arg=0x7ffff6a3d4b0)
    at /rust/git/checkouts/rust-rocksdb-a9a28e74c6ead8ef/d60144d/librocksdb_sys/rocksdb/util/threadpool_imp.cc:307
#10 0x0000555557177330 in execute_native_thread_routine ()
#11 0x00007ffff7bc6ea5 in start_thread () from /lib64/libpthread.so.0
#12 0x00007ffff72cd8dd in clone () from /lib64/libc.so.6
```

**Comment by yiwu-arbug** [comment]
will check
